import {installGPUHelp} from './gpu-help.js';
import {installI18n,translatePage,tr} from './i18n.js';
import {validateModel,readModelFiles} from './import-model.js';
import {TinyModel,softmax} from './model.js';
import {AtlasScene} from './scene.js';
const $=s=>document.getElementById(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let meta,model,scene,history=[],running=false,stop=false,current=-1;
let loading=false,activeKey="en",objectURLs=[];const entries=new Map([["cs",{base:"",label:"Atlas Mini · Čeština"}],["en",{base:"en/",label:"Atlas Mini · English"}]]);
function notice(s){$('notice').hidden=!s;$('notice').textContent=s}
function inspect(id,hover=false){$('selectedWord').textContent=meta.vocab[id];$('selectedId').textContent='# '+String(id).padStart(4,'0');$('frequency').textContent=meta.counts[id]+'×';$('pinLabel').textContent=hover?'NÁHLED · KLIKNI PRO VÝBĚR':'VYBRANÝ TOKEN';let e=scene.emb.subarray(id*48,id*48+48),mx=Math.max(...Array.from(e,Math.abs));$('embedding').innerHTML=Array.from(e,(v,j)=>{let a=Math.abs(v)/mx;return `<span title="Dimenze ${j+1}: ${v.toFixed(5)}" style="background:${v>0?`rgba(121,234,219,${.15+.85*a})`:`rgba(170,154,229,${.15+.85*a})`}"></span>`}).join('');let ns=Array.from({length:1000},(_,i)=>({id:i,value:scene.similarity(id,i)})).filter(o=>o.id!==id).sort((a,b)=>b.value-a.value).slice(0,5);$('neighbors').innerHTML=ns.map(o=>`<div class="neighbor" role="button" tabindex="0" data-id="${o.id}"><span>${escape(meta.vocab[o.id])}</span><small>${o.value.toFixed(3)}</small></div>`).join('');}
function updateCount(){if(!model)return;let ids=model.tokenize($('prompt').value);$('promptCount').textContent=ids.length+' tokenů'+(ids.includes(3)?' · neznámá slova':'');}
function showStep(index){let step=history[index];if(!step)return;current=index;document.querySelectorAll('#tokenTrail button').forEach((b,i)=>b.classList.toggle('active',i===index));$('stepBadge').textContent=`Krok ${index+1} / ${history.length}`;let top=step.probs.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p).slice(0,5);$('probabilities').innerHTML=top.map(o=>`<div class="probrow"><span title="${escape(meta.vocab[o.i])}">${escape(meta.vocab[o.i])}</span><div class="bar"><i style="width:${o.p*100}%"></i></div><span>${(o.p*100).toFixed(1)}%</span></div>`).join('');$('probNote').textContent=step.temp===0?'Softmax při T = 1; vybráno deterministicky maximum.':`Rozdělení po teplotě T = ${step.temp.toFixed(2)}; vzorkování z celého slovníku.`;let l=+$('layer').value,h=+$('head').value,n=step.ids.length,t=meta.context,weights=step.attention.subarray(((l*4+h)*t+n-1)*t,((l*4+h)*t+n-1)*t+n);$('attention').innerHTML=step.ids.map((id,i)=>`<span class="attnchip" style="background:rgba(227,141,68,${.08+weights[i]*.85})" title="Pozice ${i} · váha ${weights[i].toFixed(6)}">${escape(meta.vocab[id])}<small>${(weights[i]*100).toFixed(1)}%</small></span>`).join('');scene.setSelected(step.id);inspect(step.id);let sorted=Array.from(weights,(weight,i)=>({from:step.ids[i],to:step.ids[n-1],weight})).sort((a,b)=>b.weight-a.weight).slice(0,scene.edgeCount);scene.trace=sorted;}
function readable(ids){return ids.map(i=>meta.vocab[i]).join(' ').replace(/\s+([.,!?;:])/g,'$1')}
async function run(e){e.preventDefault();if(running){stop=true;return;}let question=$('prompt').value.trim();if(!question){notice('Napiš nejdříve otázku.');return}let ids=model.prompt(question),unknown=ids.filter(x=>x===3).length;if(ids.length>=meta.context){notice(`Dotaz je příliš dlouhý. Zkrať ho pod ${meta.context-3} tokenů.`);return}notice(unknown?`${unknown} neznámých tokenů se převede na <unk>. Model zná pouze svůj malý slovník.`:'');running=true;$('modelSelect').disabled=true;$('uploadBtn').disabled=true;stop=false;history=[];scene.trace=[];$('tokenTrail').textContent='';$('answer').textContent='';$('run').textContent='■ Zastavit';$('prompt').disabled=true;let output=[],limit=+$('maxTokens').value,temp=+$('temp').value,start=performance.now(),reason='limit délky';try{for(let k=0;k<limit;k++){if(stop){reason='zastaveno';break}let input=ids.slice(-meta.context),before=performance.now(),result=await model.forward(input),logits=Array.from(result.logits);for(let blocked of [0,1,3,4,5])logits[blocked]=-1e9;let probs=softmax(logits,temp||1);let next;if(temp===0)next=logits.indexOf(Math.max(...logits));else{let r=Math.random(),sum=0;next=2;for(let i=0;i<probs.length;i++){sum+=probs[i];if(sum>=r){next=i;break}}}history.push({ids:input,id:next,probs,attention:result.attention,temp});let button=document.createElement('button');if(next===2)button.dataset.eos='true';button.textContent=next===2?'⏹ konec':meta.vocab[next];button.title=tr(`Krok ${history.length}: ${meta.vocab[next]}`);button.onclick=()=>showStep(k);$('tokenTrail').append(button);showStep(k);$('runtime').textContent=`${model.backend} · ${Math.round(performance.now()-before)} ms`;if(next===2){reason='konec odpovědi';break}output.push(next);ids.push(next);$('answer').textContent=readable(output);await new Promise(r=>setTimeout(r,240));}if(!output.length)$('answer').innerHTML='<span>Model ukončil odpověď bez textu.</span>';$('stepBadge').textContent=`${history.length} kroků · ${reason}`;$('runtime').textContent=`${((performance.now()-start)/1000).toFixed(1)} s · ${model.backend}`;}catch(error){console.error(error);notice('Výpočet selhal: '+error.message);}finally{running=false;$('modelSelect').disabled=false;$('uploadBtn').disabled=false;$('run').innerHTML='<span>▶</span> Spustit model';$('prompt').disabled=false;}}
$('aboutBtn').onclick=$('dataBtn').onclick=()=>$('about').showModal();$('about').querySelector('.close').onclick=()=>$('about').close();$('about').onclick=e=>{if(e.target===$('about')){let r=$('about').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('about').close()}};$('temp').oninput=()=>$('tempValue').textContent=(+$('temp').value).toFixed(2);$('prompt').oninput=updateCount;$('promptForm').onsubmit=run;document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{if(running)return;$('prompt').value=b.dataset.prompt;updateCount();$('prompt').focus()});$('neighbors').onclick=e=>{let el=e.target.closest('[data-id]');if(el){scene.setSelected(+el.dataset.id);inspect(+el.dataset.id)}};$('neighbors').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.target.click()}};
$('edges').oninput=()=>{scene.edgeCount=+$('edges').value;$('edgeValue').textContent=scene.edgeCount;if(current>=0)showStep(current)};$('rotate').onclick=()=>{scene.auto=!scene.auto;$('rotate').textContent=scene.auto?'Ⅱ Zastavit':'↻ Otáčení'};$('resetView').onclick=()=>scene.setMode(scene.mode);$('zoomIn').onclick=()=>{if(scene)scene.zoom=Math.max(scene.mode?.85:3,scene.zoom*.8)};$('zoomOut').onclick=()=>{if(scene)scene.zoom=Math.min(18,scene.zoom*1.25)};$('findToken').onchange=()=>{let id=meta.vocab.indexOf($('findToken').value.toLowerCase());if(id>=0){scene.setSelected(id);inspect(id)}else notice('Tento token není ve slovníku modelu.');};$('layer').onchange=$('head').onchange=()=>showStep(current);
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(!scene)return;let mode=+b.dataset.mode;if(mode&&!scene.gpu){notice('Matice s 1 000 000 buňkami vyžaduje WebGPU nebo WebGL2. V tomto prohlížeči je dostupná mapa tokenů a CPU model.');return;}document.querySelectorAll('[data-mode]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b))});scene.setMode(mode);$('sceneLabel').textContent=['EMBEDDING SPACE / PCA 3D','COSINE SIMILARITY / 1 000 × 1 000','EMBEDDING MATRIX / 1 000 × 48'][mode];$('sceneDescription').textContent=['Každý bod je jeden naučený token.','Výška a barva = podobnost v původních 48D.','Každá buňka je jedna naučená hodnota.'][mode];$('matrixInfo').textContent=['1 000 vektorů · projekce 48 → 3D','1 000 000 vztahů · skutečné kosinové podobnosti','48 000 hodnot · naučené embeddingy'][mode];document.querySelector('.viewhelp').textContent=mode?'Táhni pro otočení · Shift + táhni pro posun · kolečko pro detail':'Táhni pro otočení · kolečko pro přiblížení · klikni pro výběr'});

function graphicsStatus(view,net){
 if(view!==scene)return;
 $('gpuHelp').hidden=view.backend==='WebGPU'&&net.backend==='WebGPU';
 $('gpuBadge').textContent=view.backend==='WebGPU'?(net.backend==='WebGPU'?'WebGPU · aktivní':'WebGPU grafika · CPU model'):view.backend==='WebGL2'?'WebGL2 grafika · CPU model':'Canvas 2D · CPU model';
 document.querySelectorAll('[data-mode]').forEach(b=>{if(view.gpu||b.dataset.mode==='0'){b.removeAttribute('aria-disabled');b.removeAttribute('title')}else{b.setAttribute('aria-disabled','true');b.title='Tento pohled vyžaduje WebGPU nebo WebGL2';}});
}
async function fallbackGraphics(view,net,error){
 net.backend='CPU';
 if(view.backend!=='WebGPU'){
  view.gpu=false;view.backend='Canvas 2D';view.setMode(0);
  try{await view.initGL();}catch(glError){console.warn('WebGL2 fallback:',glError);view.gpu=false;view.backend='Canvas 2D';}
 }
 if(view!==scene)return;
 graphicsStatus(view,net);
 notice(view.backend==='WebGL2'?'WebGPU není dostupné. Plná 3D vizualizace běží přes WebGL2; model počítá CPU.':view.backend==='WebGPU'?'Grafika běží přes WebGPU; model počítá CPU.':'WebGPU ani WebGL2 nejsou dostupné. Používám jednoduchou mapu Canvas 2D a CPU model.');
 $('gpuBadge').title=error?.message||'';
}
async function configureGraphics(view,net){
 view.onContextLost=()=>{if(view!==scene)return;graphicsStatus(view,net);document.querySelector('[data-mode="0"]').click();notice('Grafický kontext byl ztracen. Model zůstává funkční na CPU. Pro obnovení 3D načti stránku znovu.');};
 try{
  if(!navigator.gpu)throw Error('Prohlížeč neposkytuje WebGPU');
  const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});
  if(!adapter)throw Error('Grafický adaptér WebGPU není dostupný');
  const device=await adapter.requestDevice();
  device.lost.then(async()=>{
   if(view!==scene||!view.running)return;
   net.backend='CPU';view.gpu=false;view.backend='Canvas 2D';view.setMode(0);
   await fallbackGraphics(view,net,Error('WebGPU kontext byl ztracen'));
   if(view===scene)document.querySelector('[data-mode="0"]').click();
  });
  await view.initGPU(device);await net.initGPU(device);
  const input=net.prompt(meta.examplesPrompt[0]).slice(-meta.context);
  const [gpu,cpu]=await Promise.all([net.gpu(input),net.cpu(input)]);
  const diff=Math.max(...gpu.logits.map((v,i)=>Math.abs(v-cpu.logits[i])));
  if(!Number.isFinite(diff)||diff>.025)throw Error('Kontrola GPU proti CPU neprošla');
  graphicsStatus(view,net);$('gpuBadge').title=`GPU/CPU ověřeno: max. odchylka logitů ${diff.toExponential(2)}`;
  device.addEventListener('uncapturederror',e=>console.error('WebGPU',e.error));
 }catch(error){console.warn(error);await fallbackGraphics(view,net,error);}
}

async function init(key='en'){if(loading||running)return;loading=true;const entry=entries.get(key);$('modelSelect').disabled=true;$('uploadBtn').disabled=true;$('run').disabled=true;$('modelStatus').textContent='Načítám model…';try{let nextMeta,weights;if(entry.meta){nextMeta=entry.meta;weights=entry.weights;}else{let [res,wr]=await Promise.all([fetch(entry.base+'model.json'),fetch(entry.base+'weights.bin')]);if(!res.ok||!wr.ok)throw Error('Model není dostupný');nextMeta=await res.json();weights=new Float32Array(await wr.arrayBuffer());}validateModel(nextMeta,weights);
 if(scene){scene.destroy();for(let id of ['scene','overlay']){let old=$(id);old.replaceWith(old.cloneNode(false));}(model.device||scene.device)?.destroy();}meta=nextMeta;activeKey=key;history=[];current=-1;$('tokenTrail').textContent='';$('answer').innerHTML='<span>Odpověď vznikne tady,<br>jeden token po druhém.</span>';$('attention').textContent='Skutečné váhy attention se zobrazí po spuštění.';$('probabilities').textContent='Model zvažuje všech 1 000 tokenů.';$('runtime').textContent='—';$('stepBadge').textContent='Připraveno';$('findToken').value='';$('tip').hidden=true;notice('');model=new TinyModel(meta,weights);scene=new AtlasScene($('scene'),$('overlay'),meta,weights,inspect);await configureGraphics(scene,model);

 $('prompt').value=meta.examplesPrompt[0];document.querySelector('.examples').innerHTML='<span>ZKUS TŘEBA</span>'+meta.examplesPrompt.slice(0,3).map(p=>`<button type="button" data-example>${escape(p)}</button>`).join('');document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{if(running)return;$('prompt').value=b.textContent;updateCount()});objectURLs.forEach(URL.revokeObjectURL);objectURLs=[];for(let [id,data,type] of [['downloadMeta',JSON.stringify(meta),'application/json'],['downloadWeights',weights,'application/octet-stream']]){let url=URL.createObjectURL(new Blob([data],{type}));objectURLs.push(url);$(id).href=url;$(id).download=id==='downloadMeta'?'model.json':'weights.bin';}document.querySelectorAll('.downloads a').forEach((a,i)=>{if(i===0){a.hidden=!entry.base&&key!=='cs';a.href=(entry.base||'')+'corpus.json'}else a.href=$(i===1?'downloadMeta':'downloadWeights').href});document.querySelectorAll('[data-mode]').forEach(b=>{if(scene.gpu||b.dataset.mode==='0'){b.removeAttribute('aria-disabled');b.removeAttribute('title');}else b.setAttribute('aria-disabled','true')});$('rotate').textContent='↻ Otáčení';$('tokenOptions').innerHTML=meta.vocab.map(v=>`<option value="${escape(v)}"></option>`).join('');scene.start();inspect(scene.selected);updateCount();$('run').disabled=false;$('loadState').hidden=true;$('modelMeta').textContent=`${meta.parameters.toLocaleString('cs-CZ')} parametrů · ${meta.examples.toLocaleString('cs-CZ')} příkladů · bez API`;$('trainingMeta').textContent=`Modelová statistika (údaje autora): ${meta.parameters.toLocaleString('cs-CZ')} parametrů · ${meta.examples.toLocaleString('cs-CZ')} příkladů · ${meta.steps} kroků · ztráta ${meta.loss.at(-1)[1].toFixed(4)} · ${(meta.projectionVariance*100).toFixed(1)} % rozptylu v PCA 3D. Trénovací ztráta není test generalizace.`;window.atlas={model,scene,meta};$('modelStatus').textContent='Model připraven.';$('modelSelect').value=key;document.querySelector('[data-mode="0"]').click();}catch(e){console.error(e);$('loadState').textContent='Model se nepodařilo načíst. Obnov stránku.';notice(e.message);$('modelStatus').textContent='Model se nepodařilo načíst.';$('modelSelect').value=activeKey;}finally{loading=false;$('modelSelect').disabled=false;$('uploadBtn').disabled=false;$('run').disabled=!model;translatePage();}}
$('modelSelect').onchange=()=>init($('modelSelect').value);$('uploadBtn').onclick=()=>$('modelFiles').click();$('modelFiles').onchange=async()=>{try{let entry=await readModelFiles(Array.from($('modelFiles').files));let key='local-'+Date.now();entries.set(key,entry);let opt=document.createElement('option');opt.value=key;opt.textContent=entry.label+' · local';$('modelSelect').append(opt);await init(key);}catch(e){notice(e.message);}finally{$('modelFiles').value='';}};
installGPUHelp($('gpuHelp'),$('gpuDetails'),$('gpuSummary'));
installI18n();init();
