const dictionary=await fetch('translations.json').then(r=>{if(!r.ok)throw Error('Translation file unavailable');return r.json()});
let language='en';try{let saved=localStorage.getItem('atlas-language');if(['cs','en','de'].includes(saved))language=saved}catch{}
const originals=new WeakMap(),attributes=new WeakMap();let observer;
const terms={
 '⏹ konec':['⏹ end','⏹ Ende'],'GPU/CPU ověřeno: max. odchylka logitů':['GPU/CPU verified: max. logit deviation','GPU/CPU geprüft: maximale Logit-Abweichung'],'limit délky':['length limit','Längenlimit'],'zastaveno':['stopped','angehalten'],'konec odpovědi':['end of response','Antwortende'],'neznámá slova':['unknown words','unbekannte Wörter'],'neznámých tokenů se převede na <unk>. Model zná pouze svůj malý slovník.':['unknown tokens will become <unk>. The model only knows its small vocabulary.','unbekannte Token werden zu <unk>. Das Modell kennt nur sein kleines Vokabular.'],
 'Grafika běží na GPU;':['Graphics run on the GPU;','Die Grafik läuft auf der GPU;'],'Zobrazuji zjednodušenou mapu;':['Showing a simplified map;','Vereinfachte Karte wird angezeigt;'],'odpovědi počítá CPU.':['responses are computed on the CPU.','Antworten werden auf der CPU berechnet.'],'Výpočet selhal:':['Computation failed:','Berechnung fehlgeschlagen:'],'Kosinová podobnost:':['Cosine similarity:','Kosinusähnlichkeit:'],'Hodnota:':['Value:','Wert:'],'dimenze':['dimension','Dimension'],'Dimenze':['Dimension','Dimension'],'Pozice':['Position','Position'],'váha':['weight','Gewicht'],'CPU náhled':['CPU preview','CPU-Vorschau'],'sloupce: tokeny 0…999':['columns: tokens 0…999','Spalten: Token 0…999'],'sloupce: dimenze 1…48':['columns: dimensions 1…48','Spalten: Dimensionen 1…48'],
 'Modelová statistika (údaje autora):':['Model statistics (author-provided):','Modellstatistik (Angaben des Autors):'],'parametrů':['parameters','Parameter'],'příkladů':['examples','Beispiele'],'kroků':['steps','Schritte'],'bez API':['no API','ohne API'],'ztráta':['loss','Verlust'],'rozptylu v PCA 3D':['variance in PCA 3D','Varianz in PCA 3D'],'Trénovací ztráta není test generalizace.':['Training loss is not a generalization test.','Der Trainingsverlust ist kein Generalisierungstest.']};
export function tr(s){if(language==='cs')return s;let v=s.trim();if(dictionary[v])return s.replace(v,dictionary[v][language]);let idx=language==='en'?0:1;
 if(/^Krok \d+/.test(v))return v.replace('Krok',idx===0?'Step':'Schritt');
 if(/^(—|\d+) tokenů/.test(v))return v.replace('tokenů',idx===0?'tokens':'Token').replace('neznámá slova',terms['neznámá slova'][idx]);
 if(v.startsWith('Rozdělení po teplotě T = '))return v.replace('Rozdělení po teplotě T = ',idx===0?'Distribution at temperature T = ':'Verteilung bei Temperatur T = ').replace('; vzorkování z celého slovníku.',idx===0?'; sampling from the full vocabulary.':'; Stichprobe aus dem gesamten Vokabular.');
 if(v.startsWith('Dotaz je příliš dlouhý.'))return v.replace('Dotaz je příliš dlouhý. Zkrať ho pod ',idx===0?'The question is too long. Shorten it to fewer than ':'Die Frage ist zu lang. Kürze sie auf weniger als ').replace(' tokenů.',idx===0?' tokens.':' Token.');
 let out=s;for(let [cs,arr] of Object.entries(terms).sort((a,b)=>b[0].length-a[0].length))out=out.split(cs).join(arr[idx]);
 for(let [cs,arr] of Object.entries(dictionary).filter(([k])=>k.length>18).sort((a,b)=>b[0].length-a[0].length))if(out.includes(cs))out=out.split(cs).join(arr[language]);
 out=out.replace(/× v datech · 48 rozměrů/g,idx===0?'× in data · 48 dimensions':'× in den Daten · 48 Dimensionen');return out;
}
function skip(el){return !el||el.closest('script,style,textarea,#tokenOptions,#neighbors,#embedding,#selectedWord,#tokenTrail button:not([data-eos]),#probabilities .probrow,.attnchip,[data-example]')||(el.closest('#answer')&&!document.querySelector('#answer span'))||(el.tagName==='OPTION'&&el.value.startsWith('local-'));}
export function translatePage(){observer?.disconnect();document.documentElement.lang=language;document.title=tr('Token Atlas — Uvnitř jazykového modelu');let walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){let n=walker.currentNode;if(skip(n.parentElement))continue;let state=originals.get(n);if(!state||n.data!==state.rendered)state={source:n.data};let rendered=tr(state.source);if(n.data!==rendered)n.data=rendered;state.rendered=rendered;originals.set(n,state)}for(let el of document.querySelectorAll('[title],[aria-label],[placeholder]')){if(skip(el))continue;let states=attributes.get(el)||{};for(let key of ['title','aria-label','placeholder']){if(!el.hasAttribute(key))continue;let value=el.getAttribute(key),s=states[key];if(!s||value!==s.rendered)s={source:value};let rendered=tr(s.source);if(value!==rendered)el.setAttribute(key,rendered);s.rendered=rendered;states[key]=s;}attributes.set(el,states)}observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});}
export function installI18n(){const select=document.getElementById('language');select.value=language;select.onchange=()=>{language=select.value;try{localStorage.setItem('atlas-language',language)}catch{}translatePage();};observer=new MutationObserver(()=>translatePage());translatePage();}
