export function softmax(a,temp=1){let max=Math.max(...a),v=Array.from(a,x=>Math.exp((x-max)/temp)),s=v.reduce((a,b)=>a+b,0);return v.map(x=>x/s)}
export class TinyModel{
 constructor(meta,weights){this.m=meta;this.w=weights;this.vocab=new Map(meta.vocab.map((v,i)=>[v,i]));this.D=meta.d;this.T=meta.context;this.H=meta.heads;this.V=meta.vocab.length;this.backend='CPU';}
 get(k){let o=this.m.offsets[k];return this.w.subarray(o.offset,o.offset+o.shape.reduce((a,b)=>a*b,1))}
 tokenize(s){return (s.toLowerCase().match(/[\p{L}\p{N}_]+|[^\p{L}\p{N}_\s]/gu)||[]).map(t=>this.vocab.get(t)??3)}
 prompt(s){return [1,4,...this.tokenize(s),5]}
 linear(a,key){let w=this.get(key+'.weight'),b=this.get(key+'.bias'),out=new Float32Array(b.length);for(let i=0;i<b.length;i++){let z=b[i];for(let j=0;j<a.length;j++)z+=a[j]*w[i*a.length+j];out[i]=z}return out}
 norm(a,key){let w=this.get(key+'.weight'),b=this.get(key+'.bias'),mean=a.reduce((s,v)=>s+v,0)/a.length,v=a.reduce((s,v)=>s+(v-mean)**2,0)/a.length;return Float32Array.from(a,(x,i)=>(x-mean)/Math.sqrt(v+1e-5)*w[i]+b[i])}
 async cpu(ids){let {D,T,H,V}=this,n=ids.length,e=this.get('emb.weight'),p=this.get('pos.weight'),x=ids.map((id,t)=>Float32Array.from({length:D},(_,j)=>e[id*D+j]+p[t*D+j])),att=new Float32Array(this.m.layers*H*T*T),hd=D/H;
 for(let l=0;l<this.m.layers;l++){let key='blocks.'+l,qs=x.map(a=>this.linear(this.norm(a,key+'.n1'),key+'.qkv'));
 x=x.map((a,t)=>{let z=new Float32Array(D);for(let h=0;h<H;h++){let scores=[];for(let s=0;s<=t;s++){let dot=0;for(let j=0;j<hd;j++)dot+=qs[t][h*hd+j]*qs[s][D+h*hd+j];scores.push(dot/Math.sqrt(hd))}let probs=softmax(scores);for(let s=0;s<=t;s++){att[((l*H+h)*T+t)*T+s]=probs[s];for(let j=0;j<hd;j++)z[h*hd+j]+=probs[s]*qs[s][2*D+h*hd+j]}}let out=this.linear(z,key+'.proj');return Float32Array.from(a,(v,j)=>v+out[j])});
 x=x.map(a=>{let z=this.linear(this.norm(a,key+'.n2'),key+'.fc');z=Float32Array.from(z,v=>.5*v*(1+Math.tanh(Math.sqrt(2/Math.PI)*(v+.044715*v*v*v))));let out=this.linear(z,key+'.out');return Float32Array.from(a,(v,j)=>v+out[j])})}
 return {logits:this.linear(this.norm(x[n-1],'norm'),'head'),attention:att};}
 async initGPU(device){this.device=device;let {D,T,H,V}=this;let off=k=>this.m.offsets[k].offset;let sel=key=>`select(${off('blocks.0.'+key)}u,${off('blocks.1.'+key)}u,p.layer==1u)`;
 let code=`struct Params { n:u32, layer:u32, stage:u32, unused:u32 }; @group(0) @binding(0) var<uniform> p:Params; @group(0) @binding(1) var<storage,read> w:array<f32>; @group(0) @binding(2) var<storage,read> ids:array<u32>; @group(0) @binding(3) var<storage,read_write> x:array<f32>; @group(0) @binding(4) var<storage,read_write> qkv:array<f32>; @group(0) @binding(5) var<storage,read_write> att:array<f32>; @group(0) @binding(6) var<storage,read_write> logits:array<f32>;
 @compute @workgroup_size(64) fn main(@builtin(global_invocation_id) gid:vec3<u32>){let t=gid.x;
 if(p.stage==4u){if(t>=${V}u){return;}let pos=(p.n-1u)*${D}u;var mean=0.;for(var j=0u;j<${D}u;j++){mean+=x[pos+j];}mean/=${D}.;var variance=0.;for(var j=0u;j<${D}u;j++){let z=x[pos+j]-mean;variance+=z*z;}let inv=inverseSqrt(variance/${D}.+0.00001);var sum=w[${off('head.bias')}u+t];for(var j=0u;j<${D}u;j++){let z=(x[pos+j]-mean)*inv*w[${off('norm.weight')}u+j]+w[${off('norm.bias')}u+j];sum+=z*w[${off('head.weight')}u+t*${D}u+j];}logits[t]=sum;return;}
 if(t>=p.n){return;}let pos=t*${D}u;
 if(p.stage==0u){for(var j=0u;j<${D}u;j++){x[pos+j]=w[${off('emb.weight')}u+ids[t]*${D}u+j]+w[${off('pos.weight')}u+pos+j];}return;}
 if(p.stage==1u || p.stage==3u){var mean=0.;for(var j=0u;j<${D}u;j++){mean+=x[pos+j];}mean/=${D}.;var variance=0.;for(var j=0u;j<${D}u;j++){let z=x[pos+j]-mean;variance+=z*z;}let inv=inverseSqrt(variance/${D}.+0.00001);var z:array<f32,${D}>;let nw=select(${sel('n1.weight')},${sel('n2.weight')},p.stage==3u);let nb=select(${sel('n1.bias')},${sel('n2.bias')},p.stage==3u);for(var j=0u;j<${D}u;j++){z[j]=(x[pos+j]-mean)*inv*w[nw+j]+w[nb+j];}
 if(p.stage==1u){for(var i=0u;i<${3*D}u;i++){var sum=w[${sel('qkv.bias')}+i];for(var j=0u;j<${D}u;j++){sum+=z[j]*w[${sel('qkv.weight')}+i*${D}u+j];}qkv[t*${3*D}u+i]=sum;}return;}
 var f:array<f32,${2*D}>;for(var i=0u;i<${2*D}u;i++){var sum=w[${sel('fc.bias')}+i];for(var j=0u;j<${D}u;j++){sum+=z[j]*w[${sel('fc.weight')}+i*${D}u+j];}f[i]=0.5*sum*(1.+tanh(0.7978845608*(sum+0.044715*sum*sum*sum)));}for(var i=0u;i<${D}u;i++){var sum=w[${sel('out.bias')}+i];for(var j=0u;j<${2*D}u;j++){sum+=f[j]*w[${sel('out.weight')}+i*${2*D}u+j];}x[pos+i]+=sum;}return;}
 if(p.stage==2u){var z:array<f32,${D}>;for(var h=0u;h<${H}u;h++){var scores:array<f32,${T}>;var mx=-1e30;for(var s=0u;s<=t;s++){var dot=0.;for(var j=0u;j<${D/H}u;j++){dot+=qkv[t*${3*D}u+h*${D/H}u+j]*qkv[s*${3*D}u+${D}u+h*${D/H}u+j];}scores[s]=dot/${Math.sqrt(D/H)};mx=max(mx,scores[s]);}var total=0.;for(var s=0u;s<=t;s++){scores[s]=exp(scores[s]-mx);total+=scores[s];}for(var s=0u;s<=t;s++){let a=scores[s]/total;att[((p.layer*${H}u+h)*${T}u+t)*${T}u+s]=a;for(var j=0u;j<${D/H}u;j++){z[h*${D/H}u+j]+=a*qkv[s*${3*D}u+${2*D}u+h*${D/H}u+j];}}}for(var i=0u;i<${D}u;i++){var sum=w[${sel('proj.bias')}+i];for(var j=0u;j<${D}u;j++){sum+=z[j]*w[${sel('proj.weight')}+i*${D}u+j];}x[pos+i]+=sum;}}
 }`;
 const module=device.createShaderModule({code});let info=await module.getCompilationInfo();let errors=info.messages.filter(m=>m.type==='error');if(errors.length)throw Error(errors.map(e=>e.message).join('; '));
 this.pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});
 const buf=(size,usage,data)=>{let b=device.createBuffer({size,usage});if(data)device.queue.writeBuffer(b,0,data);return b};const S=GPUBufferUsage.STORAGE,C=GPUBufferUsage.COPY_DST;
 this.wbuf=buf(this.w.byteLength,S|C,this.w);this.ibuf=buf(T*4,S|C);this.xbuf=buf(T*D*4,S);this.qbuf=buf(T*D*3*4,S);this.abuf=buf(2*H*T*T*4,S|GPUBufferUsage.COPY_SRC);this.lbuf=buf(V*4,S|GPUBufferUsage.COPY_SRC);this.read=buf(V*4+2*H*T*T*4,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST);this.backend='WebGPU';
 }
 async gpu(ids){let device=this.device,n=ids.length;device.queue.writeBuffer(this.ibuf,0,new Uint32Array(ids));let enc=device.createCommandEncoder(),uniforms=[];
 for(let [stage,layer] of [[0,0],[1,0],[2,0],[3,0],[1,1],[2,1],[3,1],[4,0]]){let u=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(u,0,new Uint32Array([n,layer,stage,0]));uniforms.push(u);let bind=device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[u,this.wbuf,this.ibuf,this.xbuf,this.qbuf,this.abuf,this.lbuf].map((buffer,binding)=>({binding,resource:{buffer}}))});let pass=enc.beginComputePass();pass.setPipeline(this.pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil((stage===4?this.V:n)/64));pass.end();}
 enc.copyBufferToBuffer(this.lbuf,0,this.read,0,this.V*4);enc.copyBufferToBuffer(this.abuf,0,this.read,this.V*4,this.abuf.size);device.queue.submit([enc.finish()]);await this.read.mapAsync(GPUMapMode.READ);let a=new Float32Array(this.read.getMappedRange().slice(0));this.read.unmap();uniforms.forEach(u=>u.destroy());return {logits:a.slice(0,this.V),attention:a.slice(this.V)};
 }
 async forward(ids){ids=ids.slice(-this.T);return this.backend==='WebGPU'?this.gpu(ids):this.cpu(ids)}
}
