import {WebGL2Renderer} from './webgl2.js';
import {tr} from './i18n.js';
export class AtlasScene{
 constructor(canvas,overlay,meta,weights,onPick){this.backend='Canvas 2D';this.gpu=false;this.canvas=canvas;this.overlay=overlay;this.ctx=overlay.getContext('2d');this.m=meta;this.onPick=onPick;this.mode=0;this.selected=Math.max(0,meta.vocab.indexOf('token'));this.hover=-1;this.yaw=.25;this.pitch=.15;this.zoom=7;this.pan=[0,0];this.auto=false;this.edgeCount=18;this.trace=[];this.positions=meta.coords;this.emb=weights.subarray(meta.offsets['emb.weight'].offset,meta.offsets['emb.weight'].offset+1000*48);this.norms=new Float32Array(1000);this.normed=new Float32Array(48000);for(let i=0;i<1000;i++){let n=0;for(let j=0;j<48;j++)n+=this.emb[i*48+j]**2;n=Math.sqrt(n)||1;this.norms[i]=n;for(let j=0;j<48;j++)this.normed[i*48+j]=this.emb[i*48+j]/n;}this.colors=meta.vocab.map(t=>/^\d+$/.test(t)?'#aa9ae5':'#79eadb');this.updateNeighbors();this.bindEvents();this.frames=0;this.lastTime=performance.now();this.running=true;}
 similarity(a,b){let s=0;for(let j=0;j<48;j++)s+=this.normed[a*48+j]*this.normed[b*48+j];return s}
 updateNeighbors(){this.neighbors=Array.from({length:1000},(_,i)=>({id:i,value:this.similarity(this.selected,i)})).filter(x=>x.id!==this.selected).sort((a,b)=>b.value-a.value)}
 setSelected(id){this.selected=id;this.updateNeighbors()}
 setMode(mode){this.mode=mode;this.yaw=mode?0:.25;this.pitch=mode?-.35:.15;this.zoom=mode?8:7;this.pan=[0,0]}
 project(p){let cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),xx=p[0]*cy+p[2]*sy+this.pan[0],zz=-p[0]*sy+p[2]*cy,yy=p[1]*cp-zz*sp+this.pan[1],z=p[1]*sp+zz*cp+this.zoom;return [this.width/2+xx*1.9/z*this.height/2,this.height/2-yy*1.9/z*this.height/2,z]}
 resize(){let r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;let dpr=Math.min(devicePixelRatio||1,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.overlay.width=w;this.overlay.height=h;}this.ctx.setTransform(dpr,0,0,dpr,0,0);this.dpr=dpr;}
 async initGPU(device){this.device=device;this.context=this.canvas.getContext('webgpu');if(!this.context)throw Error('WebGPU canvas není dostupný');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device,format:this.format,alphaMode:'opaque'});
 const buffer=(data,usage)=>{let b=device.createBuffer({size:data.byteLength,usage:usage|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(b,0,data);return b};let pos=new Float32Array(4000);for(let i=0;i<1000;i++){pos.set(this.positions[i],4*i);pos[i*4+3]=/^\d+$/.test(this.m.vocab[i])?1:0}this.pbuf=buffer(pos,GPUBufferUsage.STORAGE);this.ebuf=buffer(this.emb,GPUBufferUsage.STORAGE);this.nbuf=buffer(this.normed,GPUBufferUsage.STORAGE);this.sbuf=device.createBuffer({size:4000000,usage:GPUBufferUsage.STORAGE});this.uniform=device.createBuffer({size:48,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});
 const sim=device.createShaderModule({code:`@group(0) @binding(0) var<storage,read> e:array<f32>; @group(0) @binding(1) var<storage,read_write> s:array<f32>; @compute @workgroup_size(256) fn main(@builtin(global_invocation_id) id:vec3<u32>){let i=id.x;if(i>=1000000u){return;}let a=i/1000u;let b=i%1000u;var v=0.;for(var j=0u;j<48u;j++){v+=e[a*48u+j]*e[b*48u+j];}s[i]=v;}`});let pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module:sim,entryPoint:'main'}});let bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[this.nbuf,this.sbuf].map((buffer,binding)=>({binding,resource:{buffer}}))});let enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil(1e6/256));pass.end();device.queue.submit([enc.finish()]);
 const code=`struct Camera { a:vec4<f32>, b:vec4<f32>, c:vec4<f32> }; @group(0) @binding(0) var<uniform> cam:Camera; @group(0) @binding(1) var<storage,read> points:array<vec4<f32>>; @group(0) @binding(2) var<storage,read> sims:array<f32>; @group(0) @binding(3) var<storage,read> emb:array<f32>; struct Out { @builtin(position) position:vec4<f32>, @location(0) color:vec4<f32>, @location(1) uv:vec2<f32>, @location(2) mode:f32 }; fn project(p:vec3<f32>)->vec4<f32>{let cy=cos(cam.a.x);let sy=sin(cam.a.x);let cp=cos(cam.a.y);let sp=sin(cam.a.y);let xx=p.x*cy+p.z*sy+cam.c.x;let zz=-p.x*sy+p.z*cy;let yy=p.y*cp-zz*sp+cam.c.y;let z=p.y*sp+zz*cp+cam.a.z;return vec4<f32>(xx*1.9/cam.a.w,yy*1.9,(z-0.1)*0.98,z);}
 @vertex fn vs(@builtin(vertex_index) vertex:u32,@builtin(instance_index) i:u32)->Out{var corners=array<vec2<f32>,6>(vec2(-1.,-1.),vec2(1.,-1.),vec2(-1.,1.),vec2(-1.,1.),vec2(1.,-1.),vec2(1.,1.));let uv=corners[vertex];let mode=u32(cam.b.z);var p:vec3<f32>;var color:vec3<f32>;var radius=2.;if(mode==0u){p=points[i].xyz;color=mix(vec3(.35,.87,.82),vec3(.63,.55,.88),points[i].w);if(i==u32(cam.b.w)){color=vec3(1.,.68,.39);radius=6.;}let pr=project(p);var out:Out;out.position=pr+vec4(uv.x*radius*2./cam.b.x*pr.w,uv.y*radius*2./cam.b.y*pr.w,0.,0.);out.color=vec4(color,.88);out.uv=uv;out.mode=0.;return out;}
 if(mode==1u){let row=i/1000u;let col=i%1000u;let v=sims[i];p=vec3((f32(col)/999.-.5)*6.,(.5-f32(row)/999.)*6.,v*.6);p+=vec3(uv.x*.003,uv.y*.003,0.);color=mix(vec3(.028,.055,.09),vec3(.43,.94,.83),max(0.,v));color=mix(color,vec3(.5,.31,.72),max(0.,-v));if(row==u32(cam.b.w)||col==u32(cam.b.w)){color=mix(color,vec3(1.,.64,.35),.7);}}
 else{let row=i/48u;let col=i%48u;let v=emb[i];p=vec3((f32(col)/47.-.5)*6.,(.5-f32(row)/999.)*6.,v*.10);p+=vec3(uv.x*.059,uv.y*.003,0.);color=mix(vec3(.06,.1,.15),vec3(.43,.94,.83),clamp(v*.5,0.,1.));color=mix(color,vec3(.6,.45,.86),clamp(-v*.5,0.,1.));if(row==u32(cam.b.w)){color=vec3(1.,.68,.4);}}
 var out:Out;out.position=project(p);out.color=vec4(color,1.);out.uv=uv;out.mode=f32(mode);return out;}
 @fragment fn fs(in:Out)->@location(0) vec4<f32>{if(in.mode<.5){let r=length(in.uv);if(r>1.){discard;}return vec4(in.color.rgb,in.color.a*(1.-smoothstep(.35,1.,r)));}return in.color;}`;
 let mod=device.createShaderModule({code});let errors=(await mod.getCompilationInfo()).messages.filter(x=>x.type==='error');if(errors.length)throw Error(errors.map(x=>x.message).join(';'));this.renderPipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module:mod,entryPoint:'vs'},fragment:{module:mod,entryPoint:'fs',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list'}});this.bind=device.createBindGroup({layout:this.renderPipeline.getBindGroupLayout(0),entries:[this.uniform,this.pbuf,this.sbuf,this.ebuf].map((buffer,binding)=>({binding,resource:{buffer}}))});this.gpu=true;this.backend='WebGPU';}
 async initGL(){
  // A canvas cannot switch context type after getContext('webgpu').
  this.observer?.disconnect();this.context?.unconfigure();
  const old=this.canvas;this.canvas=old.cloneNode(false);old.replaceWith(this.canvas);this.bindEvents();
  this.glRenderer=new WebGL2Renderer(this.canvas);
  try{await this.glRenderer.init(this);}catch(e){this.glRenderer.destroy();this.glRenderer=null;throw e;}
  this.gpu=true;this.backend='WebGL2';
  this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(!this.running)return;this.gpu=false;this.backend='Canvas 2D';this.setMode(0);this.onContextLost?.();});
 }
 bindEvents(){let down=null,drag=false;this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture(e.pointerId);down={x:e.clientX,y:e.clientY,button:e.button};drag=false});this.canvas.addEventListener('pointermove',e=>{let r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(down){let dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>2)drag=true;if(e.shiftKey||down.button===2){this.pan[0]+=dx/this.height*this.zoom;this.pan[1]-=dy/this.height*this.zoom}else{this.yaw+=dx*.007;this.pitch=Math.max(-1.45,Math.min(1.45,this.pitch+dy*.007));}down.x=e.clientX;down.y=e.clientY;}else{this.pick(x,y,false)}});this.canvas.addEventListener('pointerup',e=>{if(!drag){let r=this.canvas.getBoundingClientRect();this.pick(e.clientX-r.left,e.clientY-r.top,true)}down=null});this.canvas.addEventListener('pointercancel',()=>down=null);this.canvas.addEventListener('pointerleave',()=>{if(!down){document.getElementById('tip').hidden=true;this.hover=-1}});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(this.mode?.85:3,Math.min(18,this.zoom*Math.exp(e.deltaY*.001)));},{passive:false});this.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(this.canvas);}
 cell(row,col){let v=this.mode===1?this.similarity(row,col):this.emb[row*48+col];return [(col/(this.mode===1?999:47)-.5)*6,(.5-row/999)*6,v*(this.mode===1?.6:.1)]}
 pick(x,y,click){let best=-1,dist=this.mode?1000:18,col=-1;if(this.mode===0){for(let i=0;i<1000;i++){let p=this.project(this.positions[i]),d=Math.hypot(x-p[0],y-p[1]);if(d<dist){dist=d;best=i}}}else{let cols=this.mode===1?1000:48,step=this.mode===1?16:8,cstep=this.mode===1?16:2;for(let i=0;i<1000;i+=step)for(let j=0;j<cols;j+=cstep){let p=this.project(this.cell(i,j)),d=Math.hypot(x-p[0],y-p[1]);if(d<dist){dist=d;best=i;col=j}}let bi=best,bj=col;for(let i=Math.max(0,bi-step);i<Math.min(1000,bi+step+1);i++)for(let j=Math.max(0,bj-cstep);j<Math.min(cols,bj+cstep+1);j++){let p=this.project(this.cell(i,j)),d=Math.hypot(x-p[0],y-p[1]);if(d<dist){dist=d;best=i;col=j}}if(dist>25)best=-1;}
 let tip=document.getElementById('tip');tip.hidden=best<0;if(best>=0){tip.textContent=tr(this.mode===1?`${this.m.vocab[best]} × ${this.m.vocab[col]}\nKosinová podobnost: ${this.similarity(best,col).toFixed(4)}`:this.mode===2?`${this.m.vocab[best]} · dimenze ${col+1}\nHodnota: ${this.emb[best*48+col].toFixed(4)}`:`${this.m.vocab[best]}  #${best}\n${this.m.counts[best]}× v datech · 48 rozměrů`);tip.style.left=Math.min(x+14,this.width-210)+'px';tip.style.top=Math.min(y+14,this.height-70)+'px';this.hover=best;if(click){this.setSelected(best);this.onPick(best)}else if(this.mode===0)this.onPick(best,true);}else this.hover=-1;}
 drawOverlay(){let ctx=this.ctx;ctx.clearRect(0,0,this.width,this.height);if(this.mode!==0){ctx.fillStyle='#849cad';ctx.font='11px monospace';ctx.fillText(tr(this.mode===1?'sloupce: tokeny 0…999':'sloupce: dimenze 1…48'),24,this.height-75);return}let center=this.project([0,0,0]);ctx.lineWidth=.6;for(let axis=0;axis<3;axis++){let a=[0,0,0],b=[0,0,0];a[axis]=-3.4;b[axis]=3.4;let p=this.project(a),q=this.project(b);ctx.strokeStyle='#304657';ctx.setLineDash([3,7]);ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#52697c';ctx.font='10px monospace';ctx.fillText('PC'+(axis+1),q[0]+5,q[1]);}
 let origin=this.project(this.positions[this.selected]);for(let o of this.neighbors.slice(0,this.edgeCount)){let p=this.project(this.positions[o.id]);ctx.strokeStyle=`rgba(121,234,219,${.10+Math.max(0,o.value)*.22})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(origin[0],origin[1]);ctx.lineTo(p[0],p[1]);ctx.stroke();}
 for(let tr of this.trace){let p=this.project(this.positions[tr.from]),q=this.project(this.positions[tr.to]);ctx.strokeStyle=`rgba(255,181,116,${.2+tr.weight*.8})`;ctx.lineWidth=1+tr.weight*5;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.stroke();let f=(performance.now()*.0004)%1;ctx.fillStyle='#ffca91';ctx.beginPath();ctx.arc(p[0]+(q[0]-p[0])*f,p[1]+(q[1]-p[1])*f,2+tr.weight*2,0,Math.PI*2);ctx.fill();}
 if(!this.gpu){for(let i=0;i<1000;i++){let p=this.project(this.positions[i]);ctx.globalAlpha=.75;ctx.fillStyle=this.colors[i];ctx.beginPath();ctx.arc(p[0],p[1],i===this.selected?5:2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
 let labels=new Set([this.selected,this.hover,...this.neighbors.slice(0,7).map(x=>x.id),...this.trace.map(t=>t.from)]);ctx.font='12px DM Sans, sans-serif';for(let i of labels){if(i<0)continue;let p=this.project(this.positions[i]);ctx.fillStyle=i===this.selected?'#ffbc83':'#b5d4d5';ctx.fillText(this.m.vocab[i],p[0]+8,p[1]-7);}ctx.strokeStyle='#ffb574';ctx.lineWidth=1;ctx.beginPath();ctx.arc(origin[0],origin[1],10,0,Math.PI*2);ctx.stroke();}
 destroy(){this.running=false;this.observer?.disconnect();this.glRenderer?.destroy();this.context?.unconfigure();}
 start(){let tick=()=>{if(!this.running)return;this.resize();if(this.auto)this.yaw+=.0015;if(this.backend==='WebGPU'){let d=this.device;d.queue.writeBuffer(this.uniform,0,new Float32Array([this.yaw,this.pitch,this.zoom,this.width/this.height,this.width,this.height,this.mode,this.selected,...this.pan,0,0]));let enc=d.createCommandEncoder(),pass=enc.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:.037,g:.061,b:.09,a:1},loadOp:'clear',storeOp:'store'}]});pass.setPipeline(this.renderPipeline);pass.setBindGroup(0,this.bind);pass.draw(6,this.mode===0?1000:this.mode===1?1000000:48000);pass.end();d.queue.submit([enc.finish()]);}else if(this.backend==='WebGL2'){this.glRenderer.draw(this);}this.drawOverlay();this.frames++;let now=performance.now();if(now-this.lastTime>1000){document.getElementById('frameStats').textContent=`${Math.round(this.frames*1000/(now-this.lastTime))} FPS · ${this.gpu?this.backend:tr('CPU náhled')}`;this.frames=0;this.lastTime=now;}requestAnimationFrame(tick)};requestAnimationFrame(tick)}
}
